### ISSUE TITLE
Crash when a negative value a greater than the greatest positive value

### ISSUE THREAD

**Issue by elrik75** [lord63/ascii_art#1]
```py
>>> import ascii_art
>>> ascii_art.Chart([1], width=90, height=12).render()
<OK>

>>> ascii_art.Chart([1, -4], width=90, height=12).render()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.9/site-packages/ascii_art/chart.py", line 21, in render
    self._plot_data()
  File "/home/elrik/Info/SecretSauce/cat-walk/venv/lib/python3.9/site-packages/ascii_art/chart.py", line 60, in _plot_data
    self.skeleton[abs(y - self.height) - 2][x] = c
IndexError: list index out of range
```

Here how to fix it:
In `chart.py:33`:
replace:
```py
    def _prepare(self):
        self.max = max(self.data)
```

with 

```py
    def _prepare(self):
        self.max = max(abs(d) for d in self.data)  # for negative data
```

**Comment by lord63** [comment]
Release v0.2.0,  should fixed this problem.

```
>>> import ascii_art
>>> from importlib.metadata import version
>>> print(version("ascii_art"))
0.2.0
>>> print(ascii_art.Chart([1, -4], width=90, height=12).render())

   4 .
     .   ░
     .   ░
     .   ░
     . █ ░
   0 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
```
